site_name: Vibe Through Code Archive
site_description: Public engineering notes on AI, Backend, System Design and Building in Public.
site_url: https://thisisankit27.github.io/5-month-roadmap/

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/favicon.ico

  font:
    text: Inter
    code: JetBrains Mono
    
  palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg